# Generated by Django 5.2.8 on 2025-11-13 19:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the event', max_length=200)),
                ('location', models.CharField(help_text='Location of the event', max_length=300)),
                ('datetime', models.DateTimeField(help_text='Date and time of the event')),
                ('details', models.TextField(blank=True, help_text='Additional details about the event')),
                ('host_user_id', models.CharField(help_text='Supabase user ID of the event host', max_length=255)),
                ('host_email', models.EmailField(help_text='Email of the event host', max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the event was created')),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text="Supabase user ID of the user who RSVP'd", max_length=255)),
                ('user_email', models.EmailField(help_text="Email of the user who RSVP'd", max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the RSVP was created')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='core.event')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('event', 'user_id')},
            },
        ),
    ]
